sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.5-dev'
matrix:
  allow_failures:
    - python: "3.5-dev"
  # include:
  #   # This is the ltd-mason documentation deployment build
  #   - python: "3.5"
  #     env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  # An editable install is needed to get coverage and flake8 to work
  # This isn't ideal since it's not testing a truly 'installed' package
  - pip install -e .
script:
  - py.test --cov postqa --flake8
  # - sphinx-build -b html -a -n -W -d docs/_build/doctree docs docs/_build/html
# after_success:
#   # ltd-mason is a no-op for regular builds with LTD_MASON_BUILD=false
#   - ltd-mason-travis --html-dir docs/_build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="post-qa"
deploy:
  provider: pypi
  user: sqre-admin
  skip_upload_docs: true
  distributions: sdist bdist_wheel
  password:
    # PyPI deployment credentials for sqre-admin
    secure: "te3dBdyzGPDjYc+UL0LDw/yHHo7Do8MTzAc+T/kpqIcvXGJR+YqJhrD165cVAERpf5o95gCCmWFbTPyLk3Lf78qr9GgNVbkXU38MkvyRn77r4ktf4zxdq7GrBLtS6iUsfmJpvfpjq0GHiZsZd4zIksfqAjoGeX+kTCbot4OZCULzZznfcfbkfwsl2bUnEP5kXL0kzfH52SgpvXM8KlMzAjLs6u8NtL1ReQ6aEJiuISS/7PhU7mb0VgyUthS9TegoL4ELPmQYLZ/aqllygohM8MTldTBiE0X2dZSASMM2cpetTMIEIIIUgC/BQ1QFHM+/Ii/AIyeVxYT8ng7af+EplrHsz9NSjR5NzlSxqvYb2Wzsznk5yvVD/DGzvfnLdz6FGZe45Jnwyj7EARf4ymakTKbybZFPt8KFexKAWXTn2Y6vdbMfNBF/SwCZsB2h2Ow6uj8Hk/uuMDw1g8mMgY/cH4Pi++rWRdVwuB+7s312rAH+wxFt80fKfpd2NqqGJH6AZJ5YBKEVpWA9HPRpAvnGe5NwbcSEX8R/QIxi0oyLzUBct/dxqcRi2+Y+ORs2LjQ7+ZCfilz2Pr7RePqBMos/zhdQL8vb3+ydzkmmcMSTfTP8CNj9V/to6Vzj9kJM6bRI6rY8PPB1ZZYgai60Zd89X88yLgeLHqBzCu3n3RioTF0="
  on:
    tags: true
    repo: lsst-sqre/post-qa
