sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.5-dev'
matrix:
  allow_failures:
    - python: "3.5-dev"
  # include:
  #   # This is the ltd-mason documentation deployment build
  #   - python: "3.5"
  #     env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - py.test --cov postqa --flake8
  # - sphinx-build -b html -a -n -W -d docs/_build/doctree docs docs/_build/html
# after_success:
#   # ltd-mason is a no-op for regular builds with LTD_MASON_BUILD=false
#   - ltd-mason-travis --html-dir docs/_build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="post-qa"

